# Generated by Django 4.2.23 on 2025-08-11 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contabill", "0001_initial"),
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="grupo_empresarial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresas",
                to="contabill.grupoempresarial",
            ),
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(
                fields=["grupo_empresarial"], name="cadastros_e_grupo_e_362b44_idx"
            ),
        ),
    ]
