# Generated by Django 4.2.23 on 2025-08-11 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupoEmpresarial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoPadrao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("padrao", "Padrão"),
                            ("recorrente", "Recorrente"),
                            ("provisao", "Provisão"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(db_index=True, max_length=20, unique=True)),
                ("descricao", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
            ],
            options={
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="contabill__codigo_628729_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Moeda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(db_index=True, max_length=10, unique=True)),
                ("descricao", models.CharField(max_length=100)),
                ("simbolo", models.CharField(max_length=10)),
            ],
            options={
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="contabill__codigo_d97a91_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Filial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=20)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filiais",
                        to="cadastros.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["empresa", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="ContaContabil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("descricao", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("A", "Analítica"), ("S", "Sintética")], max_length=1
                    ),
                ),
                (
                    "natureza",
                    models.CharField(
                        choices=[("D", "Devedora"), ("C", "Credora")], max_length=1
                    ),
                ),
                ("ordem", models.IntegerField(default=0)),
                ("nivel", models.IntegerField()),
                (
                    "classificacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Ativo"),
                            ("P", "Passivo"),
                            ("L", "Patrimônio Líquido"),
                            ("R", "Receita"),
                            ("D", "Despesa"),
                            ("C", "Custo"),
                            ("O", "Outros"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "conta_pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filhas",
                        to="contabill.contacontabil",
                    ),
                ),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("descricao", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("O", "Operacional"),
                            ("A", "Administrativo"),
                            ("C", "Comercial"),
                            ("K", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nivel", models.IntegerField(default=1)),
                (
                    "centro_custo_pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filhos",
                        to="contabill.centrocusto",
                    ),
                ),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=10)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Aberto"), ("F", "Fechado"), ("B", "Bloqueado")],
                        max_length=1,
                    ),
                ),
                ("bloqueio_lancamento", models.BooleanField(default=False)),
                ("observacao", models.CharField(blank=True, max_length=255)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="contabill__codigo_769183_idx"
                    ),
                    models.Index(
                        fields=["empresa"], name="contabill__empresa_fa859d_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="periodo",
            constraint=models.UniqueConstraint(
                fields=("empresa", "codigo"), name="uniq_periodo_empresa_codigo"
            ),
        ),
        migrations.AddIndex(
            model_name="filial",
            index=models.Index(fields=["codigo"], name="contabill__codigo_a25ef2_idx"),
        ),
        migrations.AddIndex(
            model_name="filial",
            index=models.Index(
                fields=["empresa"], name="contabill__empresa_675a91_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="filial",
            constraint=models.UniqueConstraint(
                fields=("empresa", "codigo"), name="uniq_filial_empresa_codigo"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filial",
            unique_together={("empresa", "codigo")},
        ),
        migrations.AddIndex(
            model_name="contacontabil",
            index=models.Index(fields=["codigo"], name="contabill__codigo_e859ad_idx"),
        ),
        migrations.AddIndex(
            model_name="contacontabil",
            index=models.Index(
                fields=["conta_pai"], name="contabill__conta_p_8a7c04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="centrocusto",
            index=models.Index(fields=["codigo"], name="contabill__codigo_61342b_idx"),
        ),
        migrations.AddIndex(
            model_name="centrocusto",
            index=models.Index(
                fields=["centro_custo_pai"], name="contabill__centro__b02825_idx"
            ),
        ),
    ]
