# Generated by Django 4.2.23 on 2025-08-11 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contabill", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LancamentoContabil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_lancamento", models.DateField()),
                ("data_competencia", models.DateField()),
                (
                    "tipo_lancamento",
                    models.CharField(
                        choices=[
                            ("0", "Normal"),
                            ("1", "Societário"),
                            ("2", "Fiscal"),
                            ("3", "Orçamentário"),
                            ("4", "Zeramento"),
                            ("5", "Ajuste"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("0", "Manual"),
                            ("1", "Integrado"),
                            ("2", "Importado"),
                            ("3", "Gerado"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("numero_documento", models.CharField(blank=True, max_length=50)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "codigo_externo",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LancamentoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_externo", models.CharField(blank=True, max_length=50)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "tipo_dc",
                    models.CharField(
                        choices=[("D", "Débito"), ("C", "Crédito")], max_length=1
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RateioLancamentoItemCentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RateioLancamentoItemProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SaldoCentroCustoPeriodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "debito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "credito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "saldo_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaldoContaPeriodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "debito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "credito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "saldo_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaldoProjetoPeriodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "debito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "credito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "saldo_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name="centrocusto",
            new_name="contabill_c_codigo_afc746_idx",
            old_name="contabill__codigo_61342b_idx",
        ),
        migrations.RenameIndex(
            model_name="centrocusto",
            new_name="contabill_c_centro__92e76d_idx",
            old_name="contabill__centro__b02825_idx",
        ),
        migrations.RenameIndex(
            model_name="contacontabil",
            new_name="contabill_c_codigo_3d223c_idx",
            old_name="contabill__codigo_e859ad_idx",
        ),
        migrations.RenameIndex(
            model_name="contacontabil",
            new_name="contabill_c_conta_p_9c0364_idx",
            old_name="contabill__conta_p_8a7c04_idx",
        ),
        migrations.RenameIndex(
            model_name="filial",
            new_name="contabill_f_codigo_50dbd8_idx",
            old_name="contabill__codigo_a25ef2_idx",
        ),
        migrations.RenameIndex(
            model_name="filial",
            new_name="contabill_f_empresa_088d48_idx",
            old_name="contabill__empresa_675a91_idx",
        ),
        migrations.RenameIndex(
            model_name="moeda",
            new_name="contabill_m_codigo_1aa687_idx",
            old_name="contabill__codigo_d97a91_idx",
        ),
        migrations.RenameIndex(
            model_name="periodo",
            new_name="contabill_p_codigo_ff0c30_idx",
            old_name="contabill__codigo_769183_idx",
        ),
        migrations.RenameIndex(
            model_name="periodo",
            new_name="contabill_p_empresa_0cc4ba_idx",
            old_name="contabill__empresa_fa859d_idx",
        ),
        migrations.RenameIndex(
            model_name="projeto",
            new_name="contabill_p_codigo_c2af52_idx",
            old_name="contabill__codigo_628729_idx",
        ),
        migrations.AddField(
            model_name="saldoprojetoperiodo",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contabill.periodo"
            ),
        ),
        migrations.AddField(
            model_name="saldoprojetoperiodo",
            name="projeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contabill.projeto"
            ),
        ),
        migrations.AddField(
            model_name="saldoprojetoperiodo",
            name="saldo_conta_periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saldos_projeto",
                to="contabill.saldocontaperiodo",
            ),
        ),
        migrations.AddField(
            model_name="saldocontaperiodo",
            name="conta_contabil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contabill.contacontabil",
            ),
        ),
        migrations.AddField(
            model_name="saldocontaperiodo",
            name="filial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contabill.filial"
            ),
        ),
        migrations.AddField(
            model_name="saldocontaperiodo",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contabill.periodo"
            ),
        ),
        migrations.AddField(
            model_name="saldocentrocustoperiodo",
            name="centro_custo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contabill.centrocusto"
            ),
        ),
        migrations.AddField(
            model_name="saldocentrocustoperiodo",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contabill.periodo"
            ),
        ),
        migrations.AddField(
            model_name="saldocentrocustoperiodo",
            name="saldo_conta_periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saldos_cc",
                to="contabill.saldocontaperiodo",
            ),
        ),
        migrations.AddField(
            model_name="rateiolancamentoitemprojeto",
            name="lancamento_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rateios_projeto",
                to="contabill.lancamentoitem",
            ),
        ),
        migrations.AddField(
            model_name="rateiolancamentoitemprojeto",
            name="projeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="contabill.projeto"
            ),
        ),
        migrations.AddField(
            model_name="rateiolancamentoitemcentrocusto",
            name="centro_custo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="contabill.centrocusto"
            ),
        ),
        migrations.AddField(
            model_name="rateiolancamentoitemcentrocusto",
            name="lancamento_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rateios_cc",
                to="contabill.lancamentoitem",
            ),
        ),
        migrations.AddField(
            model_name="lancamentoitem",
            name="conta_contabil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contabill.contacontabil",
            ),
        ),
        migrations.AddField(
            model_name="lancamentoitem",
            name="filial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="contabill.filial"
            ),
        ),
        migrations.AddField(
            model_name="lancamentoitem",
            name="historico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contabill.historicopadrao",
            ),
        ),
        migrations.AddField(
            model_name="lancamentoitem",
            name="lancamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="contabill.lancamentocontabil",
            ),
        ),
        migrations.AddField(
            model_name="lancamentoitem",
            name="moeda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="contabill.moeda"
            ),
        ),
        migrations.AddField(
            model_name="lancamentocontabil",
            name="filial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="contabill.filial"
            ),
        ),
        migrations.AddField(
            model_name="lancamentocontabil",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="saldoprojetoperiodo",
            constraint=models.UniqueConstraint(
                fields=("saldo_conta_periodo", "projeto", "periodo"),
                name="uniq_saldo_projeto_periodo",
            ),
        ),
        migrations.AddIndex(
            model_name="saldocontaperiodo",
            index=models.Index(
                fields=["filial", "periodo", "conta_contabil"],
                name="contabill_s_filial__c7b163_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="saldocontaperiodo",
            constraint=models.UniqueConstraint(
                fields=("conta_contabil", "filial", "periodo"),
                name="uniq_saldo_conta_periodo",
            ),
        ),
        migrations.AddConstraint(
            model_name="saldocentrocustoperiodo",
            constraint=models.UniqueConstraint(
                fields=("saldo_conta_periodo", "centro_custo", "periodo"),
                name="uniq_saldo_cc_periodo",
            ),
        ),
        migrations.AddConstraint(
            model_name="rateiolancamentoitemprojeto",
            constraint=models.UniqueConstraint(
                fields=("lancamento_item", "projeto"), name="uniq_rateio_item_projeto"
            ),
        ),
        migrations.AddConstraint(
            model_name="rateiolancamentoitemcentrocusto",
            constraint=models.UniqueConstraint(
                fields=("lancamento_item", "centro_custo"), name="uniq_rateio_item_cc"
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentoitem",
            index=models.Index(
                fields=["lancamento"], name="contabill_l_lancame_8f5aec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentoitem",
            index=models.Index(
                fields=["conta_contabil", "tipo_dc"],
                name="contabill_l_conta_c_e6b370_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentoitem",
            index=models.Index(
                fields=["filial", "moeda"], name="contabill_l_filial__55dad5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentocontabil",
            index=models.Index(
                fields=["data_competencia", "filial"],
                name="contabill_l_data_co_db0669_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentocontabil",
            index=models.Index(
                fields=["codigo_externo"], name="contabill_l_codigo__9cdbe0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentocontabil",
            index=models.Index(
                fields=["numero_documento"], name="contabill_l_numero__6fb458_idx"
            ),
        ),
    ]
