# Generated by Django 4.2.23 on 2025-08-11 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayoutImportacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("origem_sistema", models.CharField(max_length=50)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "tipo_arquivo",
                    models.CharField(
                        choices=[
                            ("csv", "csv"),
                            ("xlsx", "xlsx"),
                            ("xml", "xml"),
                            ("api", "api"),
                        ],
                        max_length=20,
                    ),
                ),
                ("delimitador", models.CharField(default=";", max_length=5)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="DePara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("codigo_externo", models.CharField(max_length=50)),
                ("descricao_externa", models.CharField(blank=True, max_length=255)),
                ("observacao", models.CharField(blank=True, max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="importacao.layoutimportacao",
                    ),
                ),
                (
                    "target_ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeParaCentroCusto",
            fields=[],
            options={
                "verbose_name": "De/Para Centro de Custo",
                "verbose_name_plural": "De/Para Centros de Custo",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("importacao.depara",),
        ),
        migrations.CreateModel(
            name="DeParaContaContabil",
            fields=[],
            options={
                "verbose_name": "De/Para Conta Contábil",
                "verbose_name_plural": "De/Para Plano de Contas",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("importacao.depara",),
        ),
        migrations.CreateModel(
            name="DeParaEmpresa",
            fields=[],
            options={
                "verbose_name": "De/Para Empresa",
                "verbose_name_plural": "De/Para Empresas",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("importacao.depara",),
        ),
        migrations.CreateModel(
            name="DeParaFilial",
            fields=[],
            options={
                "verbose_name": "De/Para Filial",
                "verbose_name_plural": "De/Para Filiais",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("importacao.depara",),
        ),
        migrations.CreateModel(
            name="DeParaHistoricoPadrao",
            fields=[],
            options={
                "verbose_name": "De/Para Histórico Padrão",
                "verbose_name_plural": "De/Para Históricos Padrão",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("importacao.depara",),
        ),
        migrations.CreateModel(
            name="DeParaMoeda",
            fields=[],
            options={
                "verbose_name": "De/Para Moeda",
                "verbose_name_plural": "De/Para Moedas",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("importacao.depara",),
        ),
        migrations.CreateModel(
            name="DeParaParceiroNegocio",
            fields=[],
            options={
                "verbose_name": "De/Para Parceiro de Negócio",
                "verbose_name_plural": "De/Para Parceiros de Negócio",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("importacao.depara",),
        ),
        migrations.CreateModel(
            name="DeParaProjeto",
            fields=[],
            options={
                "verbose_name": "De/Para Projeto",
                "verbose_name_plural": "De/Para Projetos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("importacao.depara",),
        ),
        migrations.AddIndex(
            model_name="depara",
            index=models.Index(
                fields=["layout", "target_ct"], name="importacao__layout__581b3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depara",
            index=models.Index(
                fields=["codigo_externo"], name="importacao__codigo__4a0ca1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="depara",
            constraint=models.UniqueConstraint(
                fields=("layout", "target_ct", "codigo_externo"),
                name="uq_depara_layout_target_codigo",
            ),
        ),
    ]